name: Container image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/container.yml'
      - 'Dockerfile'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'migrations/**'
      - 'src/**'
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build_package_amd64:
    name: Build AMD64 Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push container images
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildkit
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository }}:buildkit

  build_package_arm64:
    name: Build ARM64 Image
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push container images
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildkit-arm
          cache-to: type=registry,mode=max,ref=ghcr.io/${{ github.repository }}:buildkit-arm

  build-and-push:
    needs: [build_package_amd64, build_package_arm64]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Create multi-arch image tags
        env:
          SOURCE_AMD64: ghcr.io/${{ github.repository }}@${{ needs.build_package_amd64.outputs.digest }}
          SOURCE_ARM64: ghcr.io/${{ github.repository }}@${{ needs.build_package_arm64.outputs.digest }}
        run: |
          set -euo pipefail
          while read -r TAG; do
            docker buildx imagetools create \
              --tag "$TAG" \
              "$SOURCE_AMD64" \
              "$SOURCE_ARM64"
          done <<< "$(jq -r '.tags[]' <<< "$DOCKER_METADATA_OUTPUT_JSON")"

      - name: Setup CRANE
        uses: imjasonh/setup-crane@v0.4

      - name: Flatten images
        id: flatten_images
        run: |
          set -ex
          DIGEST=""
          while read -r IMG; do
            export OUT=$(crane flatten "$IMG")
            DIGEST=$(echo "$OUT" | awk 'END{print}' | cut -d'@' -f2)
          done <<< $(echo $DOCKER_METADATA_OUTPUT_JSON | jq -r '.tags[]')
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"
